using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AutoWire;

[Generator]
public sealed class AutoWireGenerator : IIncrementalGenerator
{
    // ── Attribute FQNs ─────────────────────────────────────────────────────────
    private const string ScopedFqn       = "AutoWire.ScopedAttribute";
    private const string SingletonFqn    = "AutoWire.SingletonAttribute";
    private const string TransientFqn    = "AutoWire.TransientAttribute";
    private const string TryScopedFqn    = "AutoWire.TryScopedAttribute";
    private const string TrySingletonFqn = "AutoWire.TrySingletonAttribute";
    private const string TryTransientFqn = "AutoWire.TryTransientAttribute";
    private const string OptionsFqn      = "AutoWire.AutoWireOptionsAttribute";

    // ── Diagnostics ────────────────────────────────────────────────────────────
    private static readonly DiagnosticDescriptor AW001AbstractClass = new(
        id: "AW001",
        title: "Abstract class decorated with AutoWire attribute",
        messageFormat: "Abstract class '{0}' decorated with [{1}] will not be registered. Abstract classes cannot be instantiated.",
        category: "AutoWire",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Remove the AutoWire attribute from this class, or make the class non-abstract.");

    private static readonly DiagnosticDescriptor AW002DuplicateService = new(
        id: "AW002",
        title: "Multiple non-keyed registrations for the same service type",
        messageFormat: "Multiple non-keyed implementations are registered for '{0}'. The last registration wins. Use [Key] to distinguish, or set Duplicate = DuplicateStrategy.Replace to make the winner explicit.",
        category: "AutoWire",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Use keyed services or DuplicateStrategy.Replace/Skip to make your intent clear.");

    // ── Attribute source ───────────────────────────────────────────────────────
    private const string AttributeSource = """
        // <auto-generated by AutoWire/>
        #nullable enable
        using System;

        namespace AutoWire
        {
            /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
            public enum DuplicateStrategy
            {
                /// <summary>Add the registration regardless of existing registrations (default). Last registration wins.</summary>
                Add = 0,
                /// <summary>Only register if no registration already exists for the service type (TryAdd semantics). Ideal for NuGet library authors.</summary>
                Skip = 1,
                /// <summary>Remove all existing registrations for the service type before adding this one. Makes the winner explicit.</summary>
                Replace = 2
            }

            /// <summary>Registers the decorated class as a <b>scoped</b> service via AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class ScopedAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
                public DuplicateStrategy Duplicate { get; set; } = DuplicateStrategy.Add;
                /// <summary>Registers against all non-system interfaces the class implements (or as concrete type if none).</summary>
                public ScopedAttribute() { }
                /// <summary>Registers against the specified service type only.</summary>
                public ScopedAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Registers the decorated class as a <b>singleton</b> service via AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class SingletonAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
                public DuplicateStrategy Duplicate { get; set; } = DuplicateStrategy.Add;
                /// <summary>Registers against all non-system interfaces the class implements (or as concrete type if none).</summary>
                public SingletonAttribute() { }
                /// <summary>Registers against the specified service type only.</summary>
                public SingletonAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Registers the decorated class as a <b>transient</b> service via AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TransientAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
                public DuplicateStrategy Duplicate { get; set; } = DuplicateStrategy.Add;
                /// <summary>Registers against all non-system interfaces the class implements (or as concrete type if none).</summary>
                public TransientAttribute() { }
                /// <summary>Registers against the specified service type only.</summary>
                public TransientAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a <b>scoped</b> service using TryAdd semantics —
            /// the registration is skipped if the service type is already registered.
            /// Ideal for NuGet library authors who want to provide defaults without overriding consumer registrations.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TryScopedAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                public TryScopedAttribute() { }
                public TryScopedAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a <b>singleton</b> service using TryAdd semantics —
            /// the registration is skipped if the service type is already registered.
            /// Ideal for NuGet library authors who want to provide defaults without overriding consumer registrations.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TrySingletonAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                public TrySingletonAttribute() { }
                public TrySingletonAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a <b>transient</b> service using TryAdd semantics —
            /// the registration is skipped if the service type is already registered.
            /// Ideal for NuGet library authors who want to provide defaults without overriding consumer registrations.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TryTransientAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                public TryTransientAttribute() { }
                public TryTransientAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Assembly-level options for AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
            public sealed class AutoWireOptionsAttribute : Attribute
            {
                /// <summary>
                /// The name of the generated extension method. Defaults to <c>AddAutoWireServices</c>.
                /// Override this in test projects to avoid ambiguous extension method errors when both
                /// production and test assemblies use AutoWire.
                /// <example>[assembly: AutoWire.AutoWireOptions(MethodName = "AddTestServices")]</example>
                /// </summary>
                public string MethodName { get; set; } = "AddAutoWireServices";
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoWireAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // ── Registration pipelines ─────────────────────────────────────────────
        var scoped       = CollectRegistrations(context, ScopedFqn,       "Scoped",    DuplicateStrategy.Add);
        var singleton    = CollectRegistrations(context, SingletonFqn,    "Singleton", DuplicateStrategy.Add);
        var transient    = CollectRegistrations(context, TransientFqn,    "Transient", DuplicateStrategy.Add);
        var tryScoped    = CollectRegistrations(context, TryScopedFqn,    "Scoped",    DuplicateStrategy.Skip);
        var trySingleton = CollectRegistrations(context, TrySingletonFqn, "Singleton", DuplicateStrategy.Skip);
        var tryTransient = CollectRegistrations(context, TryTransientFqn, "Transient", DuplicateStrategy.Skip);

        // ── AW001: abstract class diagnostics ─────────────────────────────────
        RegisterAbstractDiagnostics(context, ScopedFqn,       "Scoped");
        RegisterAbstractDiagnostics(context, SingletonFqn,    "Singleton");
        RegisterAbstractDiagnostics(context, TransientFqn,    "Transient");
        RegisterAbstractDiagnostics(context, TryScopedFqn,    "TryScoped");
        RegisterAbstractDiagnostics(context, TrySingletonFqn, "TrySingleton");
        RegisterAbstractDiagnostics(context, TryTransientFqn, "TryTransient");

        // ── AutoWireOptions assembly attribute ────────────────────────────────
        var methodName = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var attr = compilation.Assembly.GetAttributes()
                .FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == OptionsFqn);
            if (attr is null) return "AddAutoWireServices";
            foreach (var na in attr.NamedArguments)
                if (na.Key == "MethodName" && na.Value.Value is string s && s.Length > 0)
                    return s;
            return "AddAutoWireServices";
        });

        // ── Combine all registrations + generate ──────────────────────────────
        var all = scoped.Collect()
            .Combine(singleton.Collect())
            .Combine(transient.Collect())
            .Combine(tryScoped.Collect())
            .Combine(trySingleton.Collect())
            .Combine(tryTransient.Collect())
            .Combine(methodName);

        context.RegisterSourceOutput(all, static (ctx, combined) =>
        {
            var ((((((s, si), t), ts), tsi), tt), name) = combined;
            var registrations = s.AddRange(si).AddRange(t).AddRange(ts).AddRange(tsi).AddRange(tt);
            if (registrations.IsEmpty) return;

            ReportDuplicateServiceDiagnostics(ctx, registrations);

            ctx.AddSource(
                "AutoWireServiceCollectionExtensions.g.cs",
                SourceText.From(GenerateSource(registrations, name), Encoding.UTF8));
        });
    }

    // ── AW001 helper ──────────────────────────────────────────────────────────

    private static void RegisterAbstractDiagnostics(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn,
        string attributeName)
    {
        var abstracts = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) =>
                {
                    if (ctx.TargetSymbol is not INamedTypeSymbol { IsAbstract: true } sym) return null;
                    var loc = sym.Locations.Length > 0 ? sym.Locations[0] : Location.None;
                    return new DiagnosticInfo("AW001", loc, new[] { sym.Name, attributeName });
                })
            .Where(static d => d is not null)
            .Select(static (d, _) => d!);

        context.RegisterSourceOutput(abstracts, static (ctx, d) =>
            ctx.ReportDiagnostic(d.Create(AW001AbstractClass)));
    }

    // ── AW002 helper ──────────────────────────────────────────────────────────

    private static void ReportDuplicateServiceDiagnostics(
        SourceProductionContext ctx,
        ImmutableArray<RegistrationInfo> registrations)
    {
        // Only warn when multiple Add-strategy (non-Skip, non-Replace) registrations share a service type.
        // Skip and Replace explicitly acknowledge the duplicate — no noise.
        var seenServices = new HashSet<string>();
        foreach (var reg in registrations.Where(r => r.Key is null && r.DuplicateStrategy == DuplicateStrategy.Add))
        {
            foreach (var svc in reg.ServiceTypes)
            {
                if (!seenServices.Add(svc))
                    ctx.ReportDiagnostic(Diagnostic.Create(AW002DuplicateService, Location.None, svc));
            }
        }
    }

    // ── Registration collection ────────────────────────────────────────────────

    private static IncrementalValuesProvider<RegistrationInfo> CollectRegistrations(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn,
        string lifetime,
        DuplicateStrategy defaultStrategy)
    {
        return context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => TransformAll(ctx, lifetime, defaultStrategy))
            .SelectMany(static (arr, _) => arr);
    }

    // ── Transform ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Produces one <see cref="RegistrationInfo"/> per attribute instance on the class,
    /// enabling AllowMultiple scenarios such as registering one class against several explicit types.
    /// </summary>
    private static ImmutableArray<RegistrationInfo> TransformAll(
        GeneratorAttributeSyntaxContext ctx,
        string lifetime,
        DuplicateStrategy defaultStrategy)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return ImmutableArray<RegistrationInfo>.Empty;
        if (classSymbol.IsAbstract) return ImmutableArray<RegistrationInfo>.Empty; // AW001 reported separately

        var builder = ImmutableArray.CreateBuilder<RegistrationInfo>(ctx.Attributes.Length);
        foreach (var attr in ctx.Attributes)
        {
            var info = TransformSingle(classSymbol, attr, lifetime, defaultStrategy);
            if (info is not null) builder.Add(info);
        }
        return builder.ToImmutable();
    }

    private static RegistrationInfo? TransformSingle(
        INamedTypeSymbol classSymbol,
        AttributeData attr,
        string lifetime,
        DuplicateStrategy defaultStrategy)
    {
        ITypeSymbol? explicitServiceType = null;
        if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is ITypeSymbol st)
            explicitServiceType = st;

        string? key = null;
        var duplicateStrategy = defaultStrategy;

        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key == "Key" && namedArg.Value.Value is string k)
                key = k;
            else if (namedArg.Key == "Duplicate" && namedArg.Value.Value is int d)
                duplicateStrategy = (DuplicateStrategy)d;
        }

        // ── Open generic path ─────────────────────────────────────────────────
        if (classSymbol.IsGenericType)
        {
            var implName = GetOpenGenericName(classSymbol);
            var serviceTypes = new List<string>();

            if (explicitServiceType is INamedTypeSymbol namedExplicit && namedExplicit.IsGenericType)
            {
                serviceTypes.Add(GetOpenGenericName(namedExplicit));
            }
            else if (explicitServiceType is null)
            {
                foreach (var iface in classSymbol.AllInterfaces)
                {
                    var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
                    if (IsSystemNamespace(ns)) continue;
                    if (!iface.IsGenericType) continue;
                    var compatible = true;
                    foreach (var ta in iface.TypeArguments)
                        if (ta is not ITypeParameterSymbol) { compatible = false; break; }
                    if (compatible)
                        serviceTypes.Add(GetOpenGenericName(iface));
                }
                if (serviceTypes.Count == 0)
                    serviceTypes.Add(implName);
            }

            return new RegistrationInfo(implName, serviceTypes.ToImmutableArray(), lifetime, key, true, duplicateStrategy);
        }

        // ── Closed type path ──────────────────────────────────────────────────
        var closedServiceTypes = new List<string>();

        if (explicitServiceType is not null)
        {
            closedServiceTypes.Add(ToFullyQualified(explicitServiceType));
        }
        else
        {
            foreach (var iface in classSymbol.AllInterfaces)
            {
                var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
                if (IsSystemNamespace(ns)) continue;
                closedServiceTypes.Add(ToFullyQualified(iface));
            }
            if (closedServiceTypes.Count == 0)
                closedServiceTypes.Add(ToFullyQualified(classSymbol));
        }

        return new RegistrationInfo(
            ToFullyQualified(classSymbol),
            closedServiceTypes.ToImmutableArray(),
            lifetime,
            key,
            false,
            duplicateStrategy);
    }

    // ── Code generation ────────────────────────────────────────────────────────

    private static string GenerateSource(ImmutableArray<RegistrationInfo> registrations, string methodName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoWire/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoWire;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Auto-generated service registration. Source-generated by AutoWire — do not edit manually.</summary>");
        sb.AppendLine("public static partial class ServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all services decorated with <see cref=\"ScopedAttribute\"/>,");
        sb.AppendLine("    /// <see cref=\"SingletonAttribute\"/>, <see cref=\"TransientAttribute\"/>,");
        sb.AppendLine("    /// <see cref=\"TryScopedAttribute\"/>, <see cref=\"TrySingletonAttribute\"/>,");
        sb.AppendLine("    /// or <see cref=\"TryTransientAttribute\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        // Ordering: Add(0) first so Skip/Replace see them already registered, then Skip(1), then Replace(2).
        foreach (var reg in registrations
            .OrderBy(static r => (int)r.DuplicateStrategy)
            .ThenBy(static r => r.Lifetime)
            .ThenBy(static r => r.ImplementationType))
        {
            foreach (var svc in reg.ServiceTypes)
                EmitLine(sb, reg, svc);
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitLine(StringBuilder sb, RegistrationInfo reg, string svc)
    {
        var isSelf = svc == reg.ImplementationType;

        switch (reg.DuplicateStrategy)
        {
            case DuplicateStrategy.Replace:
                // Remove all existing registrations for this service type, then add.
                if (reg.IsOpenGeneric)
                {
                    sb.AppendLine($"        services.RemoveAll(typeof({svc}));");
                    sb.AppendLine(isSelf
                        ? $"        services.Add{reg.Lifetime}(typeof({svc}));"
                        : $"        services.Add{reg.Lifetime}(typeof({svc}), typeof({reg.ImplementationType}));");
                }
                else
                {
                    sb.AppendLine($"        services.RemoveAll<{svc}>();");
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.AddKeyed{reg.Lifetime}<{svc}>(\"{reg.Key}\");"
                            : $"        services.AddKeyed{reg.Lifetime}<{svc}, {reg.ImplementationType}>(\"{reg.Key}\");")
                        : (isSelf
                            ? $"        services.Add{reg.Lifetime}<{svc}>();"
                            : $"        services.Add{reg.Lifetime}<{svc}, {reg.ImplementationType}>();"));
                }
                break;

            case DuplicateStrategy.Skip:
                // TryAdd — skip if service type already registered.
                if (reg.IsOpenGeneric)
                {
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.TryAddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\");"
                            : $"        services.TryAddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\", typeof({reg.ImplementationType}));")
                        : (isSelf
                            ? $"        services.TryAdd{reg.Lifetime}(typeof({svc}));"
                            : $"        services.TryAdd{reg.Lifetime}(typeof({svc}), typeof({reg.ImplementationType}));"));
                }
                else
                {
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.TryAddKeyed{reg.Lifetime}<{svc}>(\"{reg.Key}\");"
                            : $"        services.TryAddKeyed{reg.Lifetime}<{svc}, {reg.ImplementationType}>(\"{reg.Key}\");")
                        : (isSelf
                            ? $"        services.TryAdd{reg.Lifetime}<{svc}>();"
                            : $"        services.TryAdd{reg.Lifetime}<{svc}, {reg.ImplementationType}>();"));
                }
                break;

            default: // DuplicateStrategy.Add
                if (reg.IsOpenGeneric)
                {
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.AddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\");"
                            : $"        services.AddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\", typeof({reg.ImplementationType}));")
                        : (isSelf
                            ? $"        services.Add{reg.Lifetime}(typeof({svc}));"
                            : $"        services.Add{reg.Lifetime}(typeof({svc}), typeof({reg.ImplementationType}));"));
                }
                else if (reg.Key is not null)
                {
                    sb.AppendLine(isSelf
                        ? $"        services.AddKeyed{reg.Lifetime}<{svc}>(\"{reg.Key}\");"
                        : $"        services.AddKeyed{reg.Lifetime}<{svc}, {reg.ImplementationType}>(\"{reg.Key}\");");
                }
                else
                {
                    sb.AppendLine(isSelf
                        ? $"        services.Add{reg.Lifetime}<{svc}>();"
                        : $"        services.Add{reg.Lifetime}<{svc}, {reg.ImplementationType}>();");
                }
                break;
        }
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private static bool IsSystemNamespace(string ns) =>
        ns == "System" || ns.StartsWith("System.", StringComparison.Ordinal);

    private static string ToFullyQualified(ITypeSymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    /// <summary>
    /// Returns the open-generic typeof() string, e.g. <c>global::MyApp.IRepository&lt;&gt;</c>.
    /// </summary>
    private static string GetOpenGenericName(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace is { IsGlobalNamespace: false } nsSym
            ? nsSym.ToDisplayString()
            : null;
        var commas = new string(',', symbol.Arity - 1);
        var prefix = ns is not null ? $"global::{ns}." : "global::";
        return $"{prefix}{symbol.Name}<{commas}>";
    }
}
