using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AutoWire;

[Generator]
public sealed class AutoWireGenerator : IIncrementalGenerator
{
    // ── Attribute FQNs ─────────────────────────────────────────────────────────
    private const string ScopedFqn            = "AutoWire.ScopedAttribute";
    private const string SingletonFqn         = "AutoWire.SingletonAttribute";
    private const string TransientFqn         = "AutoWire.TransientAttribute";
    private const string TryScopedFqn         = "AutoWire.TryScopedAttribute";
    private const string TrySingletonFqn      = "AutoWire.TrySingletonAttribute";
    private const string TryTransientFqn      = "AutoWire.TryTransientAttribute";
    private const string DecorateScopedFqn    = "AutoWire.DecorateScopedAttribute";
    private const string DecorateSingletonFqn = "AutoWire.DecorateSingletonAttribute";
    private const string DecorateTransientFqn = "AutoWire.DecorateTransientAttribute";
    private const string HostedServiceFqn     = "AutoWire.HostedServiceAttribute";
    private const string OptionsFqn           = "AutoWire.AutoWireOptionsAttribute";

    // ── Diagnostics ────────────────────────────────────────────────────────────
    private static readonly DiagnosticDescriptor AW001AbstractClass = new(
        id: "AW001",
        title: "Abstract class decorated with AutoWire attribute",
        messageFormat: "Abstract class '{0}' decorated with [{1}] will not be registered. Abstract classes cannot be instantiated.",
        category: "AutoWire",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Remove the AutoWire attribute from this class, or make the class non-abstract.");

    private static readonly DiagnosticDescriptor AW002DuplicateService = new(
        id: "AW002",
        title: "Multiple non-keyed registrations for the same service type",
        messageFormat: "Multiple non-keyed implementations are registered for '{0}'. The last registration wins. Use [Key] to distinguish, or set Duplicate = DuplicateStrategy.Replace to make the winner explicit.",
        category: "AutoWire",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Use keyed services or DuplicateStrategy.Replace/Skip to make your intent clear.");

    private static readonly DiagnosticDescriptor AW003ServiceTypeMismatch = new(
        id: "AW003",
        title: "Class does not implement the specified service type",
        messageFormat: "'{0}' does not implement '{1}'. The registration will fail at runtime.",
        category: "AutoWire",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Ensure the class implements the type passed to the attribute constructor.");

    private static readonly DiagnosticDescriptor AW004CaptiveDependency = new(
        id: "AW004",
        title: "Singleton depends on a Scoped service",
        messageFormat: "Singleton '{0}' depends on Scoped service '{1}'. The scoped service will be captured for the singleton's lifetime, bypassing scope disposal. Inject IServiceScopeFactory and create a scope explicitly instead.",
        category: "AutoWire",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Inject IServiceScopeFactory and create a scope explicitly, or change the dependency's lifetime to Singleton or Transient.");

    // ── Attribute source ───────────────────────────────────────────────────────
    private const string AttributeSource = """
        // <auto-generated by AutoWire/>
        #nullable enable
        using System;

        namespace AutoWire
        {
            /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
            public enum DuplicateStrategy
            {
                /// <summary>Add the registration regardless of existing registrations (default). Last registration wins.</summary>
                Add = 0,
                /// <summary>Only register if no registration already exists for the service type (TryAdd semantics). Ideal for NuGet library authors.</summary>
                Skip = 1,
                /// <summary>Remove all existing registrations for the service type before adding this one. Makes the winner explicit.</summary>
                Replace = 2
            }

            /// <summary>Registers the decorated class as a <b>scoped</b> service via AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class ScopedAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
                public DuplicateStrategy Duplicate { get; set; } = DuplicateStrategy.Add;
                /// <summary>Also registers the concrete type itself in addition to the interface(s). Useful when you need to inject by concrete type in tests or internal code.</summary>
                public bool IncludeSelf { get; set; }
                /// <summary>Registers against all non-system interfaces the class implements (or as concrete type if none).</summary>
                public ScopedAttribute() { }
                /// <summary>Registers against the specified service type only.</summary>
                public ScopedAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Registers the decorated class as a <b>singleton</b> service via AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class SingletonAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
                public DuplicateStrategy Duplicate { get; set; } = DuplicateStrategy.Add;
                /// <summary>Also registers the concrete type itself in addition to the interface(s). Useful when you need to inject by concrete type in tests or internal code.</summary>
                public bool IncludeSelf { get; set; }
                /// <summary>Registers against all non-system interfaces the class implements (or as concrete type if none).</summary>
                public SingletonAttribute() { }
                /// <summary>Registers against the specified service type only.</summary>
                public SingletonAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Registers the decorated class as a <b>transient</b> service via AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TransientAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Controls how duplicate registrations for the same service type are handled.</summary>
                public DuplicateStrategy Duplicate { get; set; } = DuplicateStrategy.Add;
                /// <summary>Also registers the concrete type itself in addition to the interface(s). Useful when you need to inject by concrete type in tests or internal code.</summary>
                public bool IncludeSelf { get; set; }
                /// <summary>Registers against all non-system interfaces the class implements (or as concrete type if none).</summary>
                public TransientAttribute() { }
                /// <summary>Registers against the specified service type only.</summary>
                public TransientAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a <b>scoped</b> service using TryAdd semantics —
            /// the registration is skipped if the service type is already registered.
            /// Ideal for NuGet library authors who want to provide defaults without overriding consumer registrations.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TryScopedAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Also registers the concrete type itself in addition to the interface(s). Useful when you need to inject by concrete type in tests or internal code.</summary>
                public bool IncludeSelf { get; set; }
                public TryScopedAttribute() { }
                public TryScopedAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a <b>singleton</b> service using TryAdd semantics —
            /// the registration is skipped if the service type is already registered.
            /// Ideal for NuGet library authors who want to provide defaults without overriding consumer registrations.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TrySingletonAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Also registers the concrete type itself in addition to the interface(s). Useful when you need to inject by concrete type in tests or internal code.</summary>
                public bool IncludeSelf { get; set; }
                public TrySingletonAttribute() { }
                public TrySingletonAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a <b>transient</b> service using TryAdd semantics —
            /// the registration is skipped if the service type is already registered.
            /// Ideal for NuGet library authors who want to provide defaults without overriding consumer registrations.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class TryTransientAttribute : Attribute
            {
                /// <summary>The explicit service type to register against. When null, all non-system interfaces are used.</summary>
                public Type? ServiceType { get; }
                /// <summary>Optional keyed-service key. Requires .NET 8+ / Microsoft.Extensions.DependencyInjection 8+.</summary>
                public string? Key { get; set; }
                /// <summary>Also registers the concrete type itself in addition to the interface(s). Useful when you need to inject by concrete type in tests or internal code.</summary>
                public bool IncludeSelf { get; set; }
                public TryTransientAttribute() { }
                public TryTransientAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>
            /// Registers the decorated class as a hosted background service via
            /// <c>services.AddHostedService&lt;T&gt;()</c>.
            /// The class must implement <c>Microsoft.Extensions.Hosting.IHostedService</c>
            /// or extend <c>Microsoft.Extensions.Hosting.BackgroundService</c>.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            public sealed class HostedServiceAttribute : Attribute { }

            /// <summary>
            /// Wraps the existing <b>scoped</b> registration for <paramref name="serviceType"/> with this decorator class.
            /// The inner implementation is self-registered so that the decorator can be injected with the concrete type.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class DecorateScopedAttribute : Attribute
            {
                public Type ServiceType { get; }
                /// <summary>Controls the order in which decorators are applied when multiple decorators target the same service type. Lower values are applied first (closer to the inner service). Default is 0.</summary>
                public int Order { get; set; }
                public DecorateScopedAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Wraps the existing <b>singleton</b> registration for <paramref name="serviceType"/> with this decorator class.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class DecorateSingletonAttribute : Attribute
            {
                public Type ServiceType { get; }
                /// <summary>Controls the order in which decorators are applied when multiple decorators target the same service type. Lower values are applied first (closer to the inner service). Default is 0.</summary>
                public int Order { get; set; }
                public DecorateSingletonAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Wraps the existing <b>transient</b> registration for <paramref name="serviceType"/> with this decorator class.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            public sealed class DecorateTransientAttribute : Attribute
            {
                public Type ServiceType { get; }
                /// <summary>Controls the order in which decorators are applied when multiple decorators target the same service type. Lower values are applied first (closer to the inner service). Default is 0.</summary>
                public int Order { get; set; }
                public DecorateTransientAttribute(Type serviceType) { ServiceType = serviceType; }
            }

            /// <summary>Assembly-level options for AutoWire source generation.</summary>
            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
            public sealed class AutoWireOptionsAttribute : Attribute
            {
                /// <summary>
                /// The name of the generated extension method. Defaults to <c>AddAutoWireServices</c>.
                /// Override this in test projects to avoid ambiguous extension method errors when both
                /// production and test assemblies use AutoWire.
                /// <example>[assembly: AutoWire.AutoWireOptions(MethodName = "AddTestServices")]</example>
                /// </summary>
                public string MethodName { get; set; } = "AddAutoWireServices";
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoWireAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // ── Registration pipelines ─────────────────────────────────────────────
        var scoped       = CollectRegistrations(context, ScopedFqn,       "Scoped",    DuplicateStrategy.Add);
        var singleton    = CollectRegistrations(context, SingletonFqn,    "Singleton", DuplicateStrategy.Add);
        var transient    = CollectRegistrations(context, TransientFqn,    "Transient", DuplicateStrategy.Add);
        var tryScoped    = CollectRegistrations(context, TryScopedFqn,    "Scoped",    DuplicateStrategy.Skip);
        var trySingleton = CollectRegistrations(context, TrySingletonFqn, "Singleton", DuplicateStrategy.Skip);
        var tryTransient = CollectRegistrations(context, TryTransientFqn, "Transient", DuplicateStrategy.Skip);

        // ── AW001: abstract class diagnostics ─────────────────────────────────
        RegisterAbstractDiagnostics(context, ScopedFqn,          "Scoped");
        RegisterAbstractDiagnostics(context, SingletonFqn,       "Singleton");
        RegisterAbstractDiagnostics(context, TransientFqn,       "Transient");
        RegisterAbstractDiagnostics(context, TryScopedFqn,       "TryScoped");
        RegisterAbstractDiagnostics(context, TrySingletonFqn,    "TrySingleton");
        RegisterAbstractDiagnostics(context, TryTransientFqn,    "TryTransient");
        RegisterAbstractDiagnostics(context, DecorateScopedFqn,    "DecorateScoped");
        RegisterAbstractDiagnostics(context, DecorateSingletonFqn, "DecorateSingleton");
        RegisterAbstractDiagnostics(context, DecorateTransientFqn, "DecorateTransient");
        RegisterAbstractDiagnostics(context, HostedServiceFqn,     "HostedService");

        // ── AW003: service type not implemented ───────────────────────────────
        RegisterServiceTypeMismatchDiagnostics(context, ScopedFqn);
        RegisterServiceTypeMismatchDiagnostics(context, SingletonFqn);
        RegisterServiceTypeMismatchDiagnostics(context, TransientFqn);
        RegisterServiceTypeMismatchDiagnostics(context, TryScopedFqn);
        RegisterServiceTypeMismatchDiagnostics(context, TrySingletonFqn);
        RegisterServiceTypeMismatchDiagnostics(context, TryTransientFqn);
        RegisterServiceTypeMismatchDiagnostics(context, DecorateScopedFqn);
        RegisterServiceTypeMismatchDiagnostics(context, DecorateSingletonFqn);
        RegisterServiceTypeMismatchDiagnostics(context, DecorateTransientFqn);

        // ── Hosted service pipeline ────────────────────────────────────────────
        var hostedServices = CollectHostedServices(context);

        // ── Decorator pipelines ────────────────────────────────────────────────
        var decoScoped    = CollectDecorators(context, DecorateScopedFqn,    "Scoped");
        var decoSingleton = CollectDecorators(context, DecorateSingletonFqn, "Singleton");
        var decoTransient = CollectDecorators(context, DecorateTransientFqn, "Transient");

        // ── AutoWireOptions assembly attribute ────────────────────────────────
        var methodName = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var attr = compilation.Assembly.GetAttributes()
                .FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == OptionsFqn);
            if (attr is null) return "AddAutoWireServices";
            foreach (var na in attr.NamedArguments)
                if (na.Key == "MethodName" && na.Value.Value is string s && s.Length > 0)
                    return s;
            return "AddAutoWireServices";
        });

        // ── AW004: captive dependency detection ───────────────────────────────
        RegisterCaptiveDependencyDiagnostics(context);

        // ── Combine all registrations + generate ──────────────────────────────
        var all = scoped.Collect()
            .Combine(singleton.Collect())
            .Combine(transient.Collect())
            .Combine(tryScoped.Collect())
            .Combine(trySingleton.Collect())
            .Combine(tryTransient.Collect())
            .Combine(decoScoped.Collect())
            .Combine(decoSingleton.Collect())
            .Combine(decoTransient.Collect())
            .Combine(hostedServices.Collect())
            .Combine(methodName);

        context.RegisterSourceOutput(all, static (ctx, combined) =>
        {
            var ((((((((((s, si), t), ts), tsi), tt), ds), dsi), dt), hs), name) = combined;
            var registrations = s.AddRange(si).AddRange(t).AddRange(ts).AddRange(tsi).AddRange(tt);
            var decorators    = ds.AddRange(dsi).AddRange(dt);
            if (registrations.IsEmpty && decorators.IsEmpty && hs.IsEmpty) return;

            ReportDuplicateServiceDiagnostics(ctx, registrations);

            ctx.AddSource(
                "AutoWireServiceCollectionExtensions.g.cs",
                SourceText.From(GenerateSource(registrations, decorators, hs, name), Encoding.UTF8));
        });
    }

    // ── AW001 helper ──────────────────────────────────────────────────────────

    private static void RegisterAbstractDiagnostics(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn,
        string attributeName)
    {
        var abstracts = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) =>
                {
                    if (ctx.TargetSymbol is not INamedTypeSymbol { IsAbstract: true } sym) return null;
                    var loc = sym.Locations.Length > 0 ? sym.Locations[0] : Location.None;
                    return new DiagnosticInfo("AW001", loc, new[] { sym.Name, attributeName });
                })
            .Where(static d => d is not null)
            .Select(static (d, _) => d!);

        context.RegisterSourceOutput(abstracts, static (ctx, d) =>
            ctx.ReportDiagnostic(d.Create(AW001AbstractClass)));
    }

    // ── AW003 helper ──────────────────────────────────────────────────────────

    private static void RegisterServiceTypeMismatchDiagnostics(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn)
    {
        var mismatches = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

                    foreach (var attr in ctx.Attributes)
                    {
                        if (attr.ConstructorArguments.Length == 0) continue;
                        if (attr.ConstructorArguments[0].Value is not ITypeSymbol serviceType) continue;
                        if (!ImplementsServiceType(classSymbol, serviceType))
                        {
                            var loc = classSymbol.Locations.Length > 0 ? classSymbol.Locations[0] : Location.None;
                            return new DiagnosticInfo("AW003", loc,
                                new[] { classSymbol.Name, serviceType.ToDisplayString() });
                        }
                    }
                    return null;
                })
            .Where(static d => d is not null)
            .Select(static (d, _) => d!);

        context.RegisterSourceOutput(mismatches, static (ctx, d) =>
            ctx.ReportDiagnostic(d.Create(AW003ServiceTypeMismatch)));
    }

    // ── AW004 helper ──────────────────────────────────────────────────────────

    private static void RegisterCaptiveDependencyDiagnostics(
        IncrementalGeneratorInitializationContext context)
    {
        var captive = context.CompilationProvider
            .Select(static (compilation, _) => FindCaptiveDependencies(compilation))
            .SelectMany(static (arr, _) => arr);

        context.RegisterSourceOutput(captive, static (ctx, d) =>
            ctx.ReportDiagnostic(d.Create(AW004CaptiveDependency)));
    }

    private static ImmutableArray<DiagnosticInfo> FindCaptiveDependencies(Compilation compilation)
    {
        // Step 1: collect all service FQNs that are registered as Scoped (via [Scoped] or [TryScoped])
        var scopedFqns = new HashSet<string>(StringComparer.Ordinal);
        foreach (var type in GetAllNamedTypesInNamespace(compilation.Assembly.GlobalNamespace))
        {
            if (type.IsAbstract) continue;
            if (!TypeHasAutoWireAttribute(type, ScopedFqn) &&
                !TypeHasAutoWireAttribute(type, TryScopedFqn)) continue;

            // All non-system interfaces the class implements are potential scoped service types
            foreach (var iface in type.AllInterfaces)
            {
                var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
                if (IsSystemNamespace(ns)) continue;
                scopedFqns.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                // Also add the open-generic original definition so IRepo<Order> matches IRepo<>
                if (iface.IsGenericType)
                    scopedFqns.Add(iface.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
            // Include the concrete type itself
            scopedFqns.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        if (scopedFqns.Count == 0) return ImmutableArray<DiagnosticInfo>.Empty;

        // Step 2: for each Singleton, check constructor parameters against scoped set
        var results = ImmutableArray.CreateBuilder<DiagnosticInfo>();
        foreach (var type in GetAllNamedTypesInNamespace(compilation.Assembly.GlobalNamespace))
        {
            if (type.IsAbstract) continue;
            if (!TypeHasAutoWireAttribute(type, SingletonFqn) &&
                !TypeHasAutoWireAttribute(type, TrySingletonFqn)) continue;

            foreach (var ctor in type.InstanceConstructors)
            {
                if (ctor.DeclaredAccessibility == Accessibility.Private) continue;

                foreach (var param in ctor.Parameters)
                {
                    if (param.Type is not INamedTypeSymbol paramType) continue;

                    var fqn = paramType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    if (!scopedFqns.Contains(fqn)) continue;

                    var loc = param.Locations.Length > 0
                        ? param.Locations[0]
                        : (type.Locations.Length > 0 ? type.Locations[0] : Location.None);

                    results.Add(new DiagnosticInfo("AW004", loc,
                        new[] { type.Name, paramType.Name }));
                }
            }
        }

        return results.ToImmutable();
    }

    private static bool TypeHasAutoWireAttribute(INamedTypeSymbol symbol, string attributeFqn)
    {
        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.ToDisplayString() == attributeFqn)
                return true;
        return false;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllNamedTypesInNamespace(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in GetAllNestedTypes(type))
                yield return nested;
        }
        foreach (var childNs in ns.GetNamespaceMembers())
            foreach (var type in GetAllNamedTypesInNamespace(childNs))
                yield return type;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var deep in GetAllNestedTypes(nested))
                yield return deep;
        }
    }

    private static bool ImplementsServiceType(INamedTypeSymbol classSymbol, ITypeSymbol serviceType)
    {
        // Self-registration
        if (SymbolEqualityComparer.Default.Equals(classSymbol.OriginalDefinition, serviceType.OriginalDefinition))
            return true;

        // Interface (direct or transitive, including from base classes)
        foreach (var iface in classSymbol.AllInterfaces)
            if (SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, serviceType.OriginalDefinition))
                return true;

        // Base type chain (for abstract base class registrations)
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, serviceType.OriginalDefinition))
                return true;
            baseType = baseType.BaseType;
        }

        return false;
    }

    // ── Hosted service collection ──────────────────────────────────────────────

    private static IncrementalValuesProvider<string> CollectHostedServices(
        IncrementalGeneratorInitializationContext context)
    {
        return context.SyntaxProvider
            .ForAttributeWithMetadataName(
                HostedServiceFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    if (ctx.TargetSymbol is not INamedTypeSymbol { IsAbstract: false } sym) return null;
                    return sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                })
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);
    }

    // ── AW002 helper ──────────────────────────────────────────────────────────

    private static void ReportDuplicateServiceDiagnostics(
        SourceProductionContext ctx,
        ImmutableArray<RegistrationInfo> registrations)
    {
        // Only warn when multiple Add-strategy (non-Skip, non-Replace) registrations share a service type.
        // Skip and Replace explicitly acknowledge the duplicate — no noise.
        var seenServices = new HashSet<string>();
        foreach (var reg in registrations.Where(r => r.Key is null && r.DuplicateStrategy == DuplicateStrategy.Add))
        {
            foreach (var svc in reg.ServiceTypes)
            {
                if (!seenServices.Add(svc))
                    ctx.ReportDiagnostic(Diagnostic.Create(AW002DuplicateService, Location.None, svc));
            }
        }
    }

    // ── Decorator collection ───────────────────────────────────────────────────

    private static IncrementalValuesProvider<DecoratorInfo> CollectDecorators(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn,
        string lifetime)
    {
        return context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => TransformAllDecorators(ctx, lifetime))
            .SelectMany(static (arr, _) => arr);
    }

    private static ImmutableArray<DecoratorInfo> TransformAllDecorators(
        GeneratorAttributeSyntaxContext ctx,
        string lifetime)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return ImmutableArray<DecoratorInfo>.Empty;
        if (classSymbol.IsAbstract) return ImmutableArray<DecoratorInfo>.Empty;

        var builder = ImmutableArray.CreateBuilder<DecoratorInfo>(ctx.Attributes.Length);
        foreach (var attr in ctx.Attributes)
        {
            if (attr.ConstructorArguments.Length == 0) continue;
            if (attr.ConstructorArguments[0].Value is not ITypeSymbol serviceType) continue;

            var order = 0;
            foreach (var namedArg in attr.NamedArguments)
                if (namedArg.Key == "Order" && namedArg.Value.Value is int o)
                    order = o;

            builder.Add(new DecoratorInfo(
                ToFullyQualified(classSymbol),
                ToFullyQualified(serviceType),
                lifetime,
                order));
        }
        return builder.ToImmutable();
    }

    // ── Registration collection ────────────────────────────────────────────────

    private static IncrementalValuesProvider<RegistrationInfo> CollectRegistrations(
        IncrementalGeneratorInitializationContext context,
        string attributeFqn,
        string lifetime,
        DuplicateStrategy defaultStrategy)
    {
        return context.SyntaxProvider
            .ForAttributeWithMetadataName(
                attributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => TransformAll(ctx, lifetime, defaultStrategy))
            .SelectMany(static (arr, _) => arr);
    }

    // ── Transform ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Produces one <see cref="RegistrationInfo"/> per attribute instance on the class,
    /// enabling AllowMultiple scenarios such as registering one class against several explicit types.
    /// </summary>
    private static ImmutableArray<RegistrationInfo> TransformAll(
        GeneratorAttributeSyntaxContext ctx,
        string lifetime,
        DuplicateStrategy defaultStrategy)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return ImmutableArray<RegistrationInfo>.Empty;
        if (classSymbol.IsAbstract) return ImmutableArray<RegistrationInfo>.Empty; // AW001 reported separately

        var builder = ImmutableArray.CreateBuilder<RegistrationInfo>(ctx.Attributes.Length);
        foreach (var attr in ctx.Attributes)
        {
            var info = TransformSingle(classSymbol, attr, lifetime, defaultStrategy);
            if (info is not null) builder.Add(info);
        }
        return builder.ToImmutable();
    }

    private static RegistrationInfo? TransformSingle(
        INamedTypeSymbol classSymbol,
        AttributeData attr,
        string lifetime,
        DuplicateStrategy defaultStrategy)
    {
        ITypeSymbol? explicitServiceType = null;
        if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is ITypeSymbol st)
            explicitServiceType = st;

        string? key = null;
        var duplicateStrategy = defaultStrategy;
        var includeSelf = false;

        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key == "Key" && namedArg.Value.Value is string k)
                key = k;
            else if (namedArg.Key == "Duplicate" && namedArg.Value.Value is int d)
                duplicateStrategy = (DuplicateStrategy)d;
            else if (namedArg.Key == "IncludeSelf" && namedArg.Value.Value is bool b)
                includeSelf = b;
        }

        // ── Open generic path ─────────────────────────────────────────────────
        if (classSymbol.IsGenericType)
        {
            var implName = GetOpenGenericName(classSymbol);
            var serviceTypes = new List<string>();

            if (explicitServiceType is INamedTypeSymbol namedExplicit && namedExplicit.IsGenericType)
            {
                serviceTypes.Add(GetOpenGenericName(namedExplicit));
            }
            else if (explicitServiceType is null)
            {
                foreach (var iface in classSymbol.AllInterfaces)
                {
                    var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
                    if (IsSystemNamespace(ns)) continue;
                    if (!iface.IsGenericType) continue;
                    var compatible = true;
                    foreach (var ta in iface.TypeArguments)
                        if (ta is not ITypeParameterSymbol) { compatible = false; break; }
                    if (compatible)
                        serviceTypes.Add(GetOpenGenericName(iface));
                }
                if (serviceTypes.Count == 0)
                    serviceTypes.Add(implName);
            }

            return new RegistrationInfo(implName, serviceTypes.ToImmutableArray(), lifetime, key, true, duplicateStrategy, includeSelf);
        }

        // ── Closed type path ──────────────────────────────────────────────────
        var closedServiceTypes = new List<string>();

        if (explicitServiceType is not null)
        {
            closedServiceTypes.Add(ToFullyQualified(explicitServiceType));
        }
        else
        {
            foreach (var iface in classSymbol.AllInterfaces)
            {
                var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
                if (IsSystemNamespace(ns)) continue;
                closedServiceTypes.Add(ToFullyQualified(iface));
            }
            if (closedServiceTypes.Count == 0)
                closedServiceTypes.Add(ToFullyQualified(classSymbol));
        }

        return new RegistrationInfo(
            ToFullyQualified(classSymbol),
            closedServiceTypes.ToImmutableArray(),
            lifetime,
            key,
            false,
            duplicateStrategy,
            includeSelf);
    }

    // ── Code generation ────────────────────────────────────────────────────────

    private static string GenerateSource(
        ImmutableArray<RegistrationInfo> registrations,
        ImmutableArray<DecoratorInfo> decorators,
        ImmutableArray<string> hostedServices,
        string methodName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AutoWire/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace AutoWire;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Auto-generated service registration. Source-generated by AutoWire — do not edit manually.</summary>");
        sb.AppendLine("public static partial class ServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all services decorated with <see cref=\"ScopedAttribute\"/>,");
        sb.AppendLine("    /// <see cref=\"SingletonAttribute\"/>, <see cref=\"TransientAttribute\"/>,");
        sb.AppendLine("    /// <see cref=\"TryScopedAttribute\"/>, <see cref=\"TrySingletonAttribute\"/>,");
        sb.AppendLine("    /// or <see cref=\"TryTransientAttribute\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        // Ordering: Add(0) first so Skip/Replace see them already registered, then Skip(1), then Replace(2).
        foreach (var reg in registrations
            .OrderBy(static r => (int)r.DuplicateStrategy)
            .ThenBy(static r => r.Lifetime)
            .ThenBy(static r => r.ImplementationType))
        {
            foreach (var svc in reg.ServiceTypes)
                EmitLine(sb, reg, svc);

            // IncludeSelf: also register as concrete type when not already a self-only registration.
            if (reg.IncludeSelf && !reg.ServiceTypes.Contains(reg.ImplementationType))
                EmitLine(sb, reg, reg.ImplementationType);
        }

        // ── Decorators (always after normal registrations so the inner service is present) ──
        if (!decorators.IsEmpty)
        {
            // Build compile-time map: service type → known concrete implementation type
            var serviceToConcreteMap = new Dictionary<string, string>();
            foreach (var reg in registrations.Where(static r => r.Key is null && !r.IsOpenGeneric))
                foreach (var svc in reg.ServiceTypes)
                    if (svc != reg.ImplementationType)
                        serviceToConcreteMap[svc] = reg.ImplementationType;

            // Group by (Lifetime, ServiceType) so multiple decorators targeting the same service
            // are emitted as a single chain sorted by Order (lowest = innermost).
            var groups = new Dictionary<string, List<DecoratorInfo>>(StringComparer.Ordinal);
            foreach (var dec in decorators)
            {
                var key = dec.Lifetime + "::" + dec.ServiceType;
                if (!groups.TryGetValue(key, out var list))
                    groups[key] = list = new List<DecoratorInfo>();
                list.Add(dec);
            }

            var idx = 0;
            foreach (var kvp in groups.OrderBy(static g => g.Key))
            {
                sb.AppendLine();
                var chain = kvp.Value.OrderBy(static d => d.Order).ThenBy(static d => d.DecoratorType).ToList();
                EmitDecoratorChain(sb, chain, serviceToConcreteMap, ref idx);
            }
        }

        // ── Hosted services ────────────────────────────────────────────────────
        if (!hostedServices.IsEmpty)
        {
            sb.AppendLine();
            foreach (var hs in hostedServices.OrderBy(static s => s))
                sb.AppendLine($"        services.AddHostedService<{hs}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDecoratorChain(
        StringBuilder sb,
        List<DecoratorInfo> chain,
        Dictionary<string, string> serviceToConcreteMap,
        ref int idx)
    {
        var serviceType = chain[0].ServiceType;
        var lifetime    = chain[0].Lifetime;

        sb.AppendLine($"        // [Decorate{lifetime}] chain for {serviceType} ({chain.Count} decorator(s), innermost first by Order)");

        if (serviceToConcreteMap.TryGetValue(serviceType, out var originalConcrete))
        {
            // Compile-time known inner type — emit the full chain type-safely.
            // chain[0] = innermost (lowest Order), chain[^1] = outermost (highest Order) → registered as IService.
            sb.AppendLine($"        services.RemoveAll<{serviceType}>();");
            sb.AppendLine($"        services.Add{lifetime}<{originalConcrete}>();");

            var previousType = originalConcrete;
            for (var i = 0; i < chain.Count - 1; i++)
            {
                var dec = chain[i];
                sb.AppendLine($"        services.Add{lifetime}<{dec.DecoratorType}>(sp =>");
                sb.AppendLine($"            ({dec.DecoratorType})global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
                sb.AppendLine($"                sp, typeof({dec.DecoratorType}), sp.GetRequiredService<{previousType}>()));");
                previousType = dec.DecoratorType;
            }

            var last = chain[chain.Count - 1];
            sb.AppendLine($"        services.Add{lifetime}<{serviceType}>(sp =>");
            sb.AppendLine($"            ({serviceType})global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
            sb.AppendLine($"                sp, typeof({last.DecoratorType}), sp.GetRequiredService<{previousType}>()));");
        }
        else
        {
            // Runtime fallback — apply decorators sequentially.
            // Each EmitDecorator call will self-register the prior concrete type, enabling the next in the chain to find it.
            foreach (var dec in chain)
            {
                EmitDecorator(sb, dec, serviceToConcreteMap, idx++);
                // After the first decorator, the concrete type it self-registered becomes the new inner for the next.
                serviceToConcreteMap[dec.ServiceType] = dec.DecoratorType;
            }
        }
    }

    private static void EmitDecorator(
        StringBuilder sb,
        DecoratorInfo dec,
        Dictionary<string, string> serviceToConcreteMap,
        int index)
    {
        sb.AppendLine($"        // [Decorate{dec.Lifetime}] {dec.DecoratorType} wraps {dec.ServiceType}");

        if (serviceToConcreteMap.TryGetValue(dec.ServiceType, out var concreteType))
        {
            // Compile-time known inner type — fully type-safe generated code.
            sb.AppendLine($"        services.RemoveAll<{dec.ServiceType}>();");
            sb.AppendLine($"        services.Add{dec.Lifetime}<{concreteType}>();");
            sb.AppendLine($"        services.Add{dec.Lifetime}<{dec.ServiceType}>(sp =>");
            sb.AppendLine($"            ({dec.ServiceType})global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
            sb.AppendLine($"                sp, typeof({dec.DecoratorType}), sp.GetRequiredService<{concreteType}>()));");
        }
        else
        {
            // Runtime fallback — inner type not registered via AutoWire (e.g. manually registered).
            sb.AppendLine($"        {{");
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor? __aw_dec{index} = null;");
            sb.AppendLine($"            for (var __i = services.Count - 1; __i >= 0; __i--)");
            sb.AppendLine($"                if (services[__i].ServiceType == typeof({dec.ServiceType}) && services[__i].ImplementationType != null)");
            sb.AppendLine($"                {{ __aw_dec{index} = services[__i]; break; }}");
            sb.AppendLine($"            if (__aw_dec{index} != null)");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var __aw_inner{index} = __aw_dec{index}.ImplementationType!;");
            sb.AppendLine($"                services.Remove(__aw_dec{index});");
            sb.AppendLine($"                services.Add(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe(");
            sb.AppendLine($"                    __aw_inner{index}, __aw_inner{index}, __aw_dec{index}.Lifetime));");
            sb.AppendLine($"                services.Add{dec.Lifetime}<{dec.ServiceType}>(sp =>");
            sb.AppendLine($"                    ({dec.ServiceType})global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(");
            sb.AppendLine($"                        sp, typeof({dec.DecoratorType}), sp.GetRequiredService(__aw_inner{index})));");
            sb.AppendLine($"            }}");
            sb.AppendLine($"            else");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                services.Add{dec.Lifetime}<{dec.ServiceType}, {dec.DecoratorType}>();");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }}");
        }
    }

    private static void EmitLine(StringBuilder sb, RegistrationInfo reg, string svc)
    {
        var isSelf = svc == reg.ImplementationType;

        switch (reg.DuplicateStrategy)
        {
            case DuplicateStrategy.Replace:
                // Remove all existing registrations for this service type, then add.
                if (reg.IsOpenGeneric)
                {
                    sb.AppendLine($"        services.RemoveAll(typeof({svc}));");
                    sb.AppendLine(isSelf
                        ? $"        services.Add{reg.Lifetime}(typeof({svc}));"
                        : $"        services.Add{reg.Lifetime}(typeof({svc}), typeof({reg.ImplementationType}));");
                }
                else
                {
                    sb.AppendLine($"        services.RemoveAll<{svc}>();");
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.AddKeyed{reg.Lifetime}<{svc}>(\"{reg.Key}\");"
                            : $"        services.AddKeyed{reg.Lifetime}<{svc}, {reg.ImplementationType}>(\"{reg.Key}\");")
                        : (isSelf
                            ? $"        services.Add{reg.Lifetime}<{svc}>();"
                            : $"        services.Add{reg.Lifetime}<{svc}, {reg.ImplementationType}>();"));
                }
                break;

            case DuplicateStrategy.Skip:
                // TryAdd — skip if service type already registered.
                if (reg.IsOpenGeneric)
                {
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.TryAddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\");"
                            : $"        services.TryAddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\", typeof({reg.ImplementationType}));")
                        : (isSelf
                            ? $"        services.TryAdd{reg.Lifetime}(typeof({svc}));"
                            : $"        services.TryAdd{reg.Lifetime}(typeof({svc}), typeof({reg.ImplementationType}));"));
                }
                else
                {
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.TryAddKeyed{reg.Lifetime}<{svc}>(\"{reg.Key}\");"
                            : $"        services.TryAddKeyed{reg.Lifetime}<{svc}, {reg.ImplementationType}>(\"{reg.Key}\");")
                        : (isSelf
                            ? $"        services.TryAdd{reg.Lifetime}<{svc}>();"
                            : $"        services.TryAdd{reg.Lifetime}<{svc}, {reg.ImplementationType}>();"));
                }
                break;

            default: // DuplicateStrategy.Add
                if (reg.IsOpenGeneric)
                {
                    sb.AppendLine(reg.Key is not null
                        ? (isSelf
                            ? $"        services.AddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\");"
                            : $"        services.AddKeyed{reg.Lifetime}(typeof({svc}), \"{reg.Key}\", typeof({reg.ImplementationType}));")
                        : (isSelf
                            ? $"        services.Add{reg.Lifetime}(typeof({svc}));"
                            : $"        services.Add{reg.Lifetime}(typeof({svc}), typeof({reg.ImplementationType}));"));
                }
                else if (reg.Key is not null)
                {
                    sb.AppendLine(isSelf
                        ? $"        services.AddKeyed{reg.Lifetime}<{svc}>(\"{reg.Key}\");"
                        : $"        services.AddKeyed{reg.Lifetime}<{svc}, {reg.ImplementationType}>(\"{reg.Key}\");");
                }
                else
                {
                    sb.AppendLine(isSelf
                        ? $"        services.Add{reg.Lifetime}<{svc}>();"
                        : $"        services.Add{reg.Lifetime}<{svc}, {reg.ImplementationType}>();");
                }
                break;
        }
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private static bool IsSystemNamespace(string ns) =>
        ns == "System" || ns.StartsWith("System.", StringComparison.Ordinal);

    private static string ToFullyQualified(ITypeSymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    /// <summary>
    /// Returns the open-generic typeof() string, e.g. <c>global::MyApp.IRepository&lt;&gt;</c>.
    /// </summary>
    private static string GetOpenGenericName(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace is { IsGlobalNamespace: false } nsSym
            ? nsSym.ToDisplayString()
            : null;
        var commas = new string(',', symbol.Arity - 1);
        var prefix = ns is not null ? $"global::{ns}." : "global::";
        return $"{prefix}{symbol.Name}<{commas}>";
    }
}
